server:
  port: 8080

spring:
  application:
    name: product
  profiles:
    active: dev
  config:
    import:
      - optional:configserver:http://3.34.181.222:8888/
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    config:
      label: main
  jpa:
    show-sql: true

logging:
  level:
    root: info

frontend:
  redirectUrlWithAccessTokenAndRefreshToken: http://43.201.26.253/redirect?accessToken=%s&refreshToken=%s
